dataset_name: thumos
train_split: [ 'validation' ]
val_split: [ 'test' ]
devices: 
  - cuda:0
dataset: {
  json_file: ./annotations/thumos14.json,
  feat_folder: /mnt/cephfs/dataset/m3lab_data-z/jiaqi/data/thumos/actionformer/videomae_v2/rgb_features,
  # feat_folder: /mnt/cephfs/dataset/m3lab_data-z/jiaqi/data/thumos/actionformer/videomae_v2/corrupted_rgb_features/val/blackframe_1frame/features,
  load_aug_feat: True,
  augfeat_folder: /mnt/cephfs/dataset/m3lab_data-z/jiaqi/data/thumos/actionformer/videomae_v2/corrupted_rgb_features/val/overexposure_1frame/features,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 20,
  input_dim: 1408,
  feat_stride: 4,
  num_frames: 16,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [ 0.9, 1.0 ],
  max_seq_len: 2304,
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 6.0,
  backbone_arch: [ 2, 2, 5 ],
  n_sgp_win_size: 1,
  regression_range: [ [ 0, 4 ], [ 4, 8 ], [ 8, 16 ], [ 16, 32 ], [ 32, 64 ], [ 64, 10000 ] ],
  num_bins: 16,
  k: 5,
  iou_weight_power: 0.2,
  use_trident_head: True,
  sgp_mlp_dim: 768,
  input_noise: 0.0005
}
opt: {
  learning_rate: 0.0001,
  warmup_epochs: 15,
  epochs: 45,
  weight_decay: 0.025,
}
loader: {
  batch_size: 2,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  loss_type: jsd, # 'jsd' 'kld' 'mse' 'none'
  jsd_loss_weight: 1.0,
  kld_loss_weight: 1.5,
  mse_loss_weight: 1.0,
  sample_way: center_sample, # 'center_sample' 'whole' 'both'
}
# the inference on THUMOS is quite different from EPIC-kitchens
# a major performance gain is achieved by fusing external classification scores
# doing so will require disable multiclass_nms and enable score fusion
test_cfg: {
  voting_thresh: 0.7,
  pre_nms_topk: 2000,
  max_seg_num: 2000,
  min_score: 0.001,
  multiclass_nms: True
}

change_test_feat: True
test_feat_path: /mnt/cephfs/dataset/m3lab_data-z/jiaqi/data/thumos/actionformer/videomae_v2/rgb_features
output_folder: /mnt/cephfs/dataset/m3lab_data-z/jiaqi/exp/tridet/cvpr_checkpoint/ckpt_jsd
extractor: videoMAE
